/home/data/nbc/misc-projects/Salo_PowerReplication/ddmra/ddmra/utils.py:308: RuntimeWarning: divide by zero encountered in arctanh
  z_arr = np.arctanh(r_arr)
/home/data/nbc/misc-projects/Salo_PowerReplication/ddmra/ddmra/utils.py:308: RuntimeWarning: divide by zero encountered in arctanh
  z_arr = np.arctanh(r_arr)
/home/data/nbc/misc-projects/Salo_PowerReplication/ddmra/ddmra/utils.py:308: RuntimeWarning: divide by zero encountered in arctanh
  z_arr = np.arctanh(r_arr)
/home/data/nbc/misc-projects/Salo_PowerReplication/ddmra/ddmra/utils.py:308: RuntimeWarning: divide by zero encountered in arctanh
  z_arr = np.arctanh(r_arr)
/home/data/nbc/misc-projects/Salo_PowerReplication/ddmra/ddmra/utils.py:308: RuntimeWarning: divide by zero encountered in arctanh
  z_arr = np.arctanh(r_arr)
/home/data/nbc/misc-projects/Salo_PowerReplication/ddmra/ddmra/utils.py:308: RuntimeWarning: divide by zero encountered in arctanh
  z_arr = np.arctanh(r_arr)
/home/data/nbc/misc-projects/Salo_PowerReplication/ddmra/ddmra/utils.py:308: RuntimeWarning: divide by zero encountered in arctanh
  z_arr = np.arctanh(r_arr)
/home/data/nbc/misc-projects/Salo_PowerReplication/ddmra/ddmra/utils.py:308: RuntimeWarning: divide by zero encountered in arctanh
  z_arr = np.arctanh(r_arr)
/home/data/nbc/misc-projects/Salo_PowerReplication/ddmra/ddmra/utils.py:308: RuntimeWarning: divide by zero encountered in arctanh
  z_arr = np.arctanh(r_arr)
/home/data/nbc/misc-projects/Salo_PowerReplication/ddmra/ddmra/utils.py:308: RuntimeWarning: divide by zero encountered in arctanh
  z_arr = np.arctanh(r_arr)
/home/data/nbc/misc-projects/Salo_PowerReplication/code/conda_env/lib/python3.7/site-packages/numpy/lib/function_base.py:2642: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/home/data/nbc/misc-projects/Salo_PowerReplication/code/conda_env/lib/python3.7/site-packages/numpy/lib/function_base.py:2643: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
Traceback (most recent call last):
  File "/home/data/nbc/misc-projects/Salo_PowerReplication/code/experiment-2/05_ddmra.py", line 145, in <module>
    project_dir, participants_file, target_file_pattern, confounds_pattern
  File "/home/data/nbc/misc-projects/Salo_PowerReplication/code/experiment-2/05_ddmra.py", line 98, in run_ddmra_analyses
    qc_thresh=0.2,
  File "/home/data/nbc/misc-projects/Salo_PowerReplication/ddmra/ddmra/workflows.py", line 217, in run_analyses
    qc, ts_all, edge_sorting_idx, qc_thresh, perm=False
  File "/home/data/nbc/misc-projects/Salo_PowerReplication/ddmra/ddmra/analysis.py", line 107, in scrubbing_analysis
    mean_delta_z = mean_delta_z[:, edge_sorting_idx]
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
